### ISSUE TITLE
Ask user what they are working on

### ISSUE THREAD

**Issue by ghost** [hardchor/timesheets#21]
Settings:
- [x] is active
- [x] from time
- [x] to time
- [x] weekdays

Tasks: 
- [x] "Cronjob" that checks every 15mins?
- [x] Pop up menubar
- [x] ~~add option to snooze~~
- [x] add option to turn reminder on/off

**Comment by hardchor** [comment]
Proper positioning of menubar blocked by https://github.com/electron/electron/issues/2469
